<a href="https://colab.research.google.com/github/brauliovillalobos/NeuralNetworksforDataScience/blob/main/InitialCodesOnNeuralNetworks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
X = tf.random.normal((64,64,3))

In [4]:
X.shape

TensorShape([64, 64, 3])

In [5]:
U = tf.random.normal((2,2,3))
U

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 1.381421  ,  1.5753436 , -0.13346902],
        [ 2.6583679 , -1.0537556 , -0.10446808]],

       [[-0.8461491 ,  1.1395668 ,  1.4899648 ],
        [ 0.3205878 ,  0.552356  ,  1.3513439 ]]], dtype=float32)>

In [7]:
U = tf.random.normal((1,1,3))
U

<tf.Tensor: shape=(1, 1, 3), dtype=float32, numpy=array([[[-0.8408342 , -1.0139573 , -0.80226064]]], dtype=float32)>

In [8]:
U = tf.random.normal((2,1,3))
U

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[-1.0674795 , -0.64746505, -1.646981  ]],

       [[-1.3321339 , -0.6211635 , -1.0670304 ]]], dtype=float32)>

In [9]:
U = tf.random.normal((2,2,3))
U

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.13671803, -1.5612985 , -0.13488008],
        [-0.08550176, -0.00640545, -0.47278523]],

       [[ 1.4713643 ,  0.7839827 , -0.37366232],
        [-0.9647404 , -0.08350898,  0.68478984]]], dtype=float32)>

#Batched Operations

In [10]:
X = tf.random.normal((3, 4, 5))
Y = tf.random.normal((3, 5, 10))
Z = tf.linalg.matmul(X, Y)

In [ ]:
Z

#Matrix and Element-wise operations

In [12]:
X = tf.math.exp(X) # Element-wise exponential
X = tf.linalg.expm(X) # Matrix exponential

InvalidArgumentError: ignored

#Einstein Sum

In [14]:
X = tf.random.normal(shape=[7,5,3])
Y = tf.random.normal(shape=[7,3,2])
Z = tf.einsum('bij,bjk->bik', X, Y)

#Example of Linear Approximation

In [15]:
# Function
f = lambda x: x**2 - 1.5*x

# Derivative (manual)
df = lambda x: 2*x - 1.5

# Linearization at 0.5
x = 0.5
f_linearized = lambda h: f(x) + df(x)*(h - x)

print(f(x + 0.01)) # -0.5049
print(f_linearized(x + 0.01)) # -0.5050

-0.5049
-0.505
